export { subscribeChannelMethod as subscribeChannel } from './channel'
export { handleError } from './error'
export { foldp } from './foldp'
export { map, maybeMap } from './map'
export { subscribeGenerator } from './generator'
